# services:
#   postgres:
#     image: postgres
#     ports:
#       - '5432:5432'
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgrespw
#       POSTGRES_DB: auctions
#     volumes:
#       - /pgdata:/var/lib/postgresql/data

#   mongodb:
#     image: mongo
#     ports:
#       - '27017:27017'
#     volumes:
#       - /mongodata:/data/db
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: mongopw
#       MONGO_INITDB_DATABASE: searchservice

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgrespw
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
volumes:
  pgdata:
  mongodata:
